name: Web App Deployemnt az-pac-dev
on:
  push:
    branches: 
      - master
    paths:
      - .github/workflows/az-pac-dev.yml

jobs:
  build:
    name: Web App Deployemnt - az-pac-dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          path: workflow

      - name: Login to Azure
        uses: azure/login@v1.1
        with:
         creds: ${{secrets.AZ_SPN_CREDS}}
      
      - name: policy-compliance-scans
        uses: Azure/policy-compliance-scan@v0
        with:
          scopes: |
            /subscriptions/c00d16c7-6c1f-4c03-9be1-6934a4c49682/resourcegroups/az-pac-dev/providers/Microsoft.Web/sites/pacDempApp